INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Haris Narkoteris', '2008', 'Carmelo Anthony', 'Fantastinis');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Steve Jobs', '2011', 'Javtokas', 'Siaubekas');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Kovos Klubas', '1999', 'Čakas Palanikas', 'Fikcija');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Žiedų valdovas', '1954', 'Smygolas', 'Fantastika');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Lūžio taškas', '2016', 'Kalnietis', 'Detektyvas');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Pablas Eskobaras', '2017', 'Narkotiku Baronas', 'Kriminalinis');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Silva Rerum III', '2014','Vin Diesel', 'Drama');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Leonardas Davincis', '2016', 'Tas garsus autorius', 'Menas');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Madagaskaras', '2017', 'Valinskas', 'Nuotykiu');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Alisa Stebuklu salyje', '2016', 'Baby Alice', 'Pasaka');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Drakula', '2015', 'Nielsenas', 'Siaubo');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Medžiokliniai šunys', '2017', 'Tanoka Beard', 'Siaubo');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Pimrkyse moteris', '2012', 'Linas Kleiza', 'Siaubekas');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Protas turi širdy', '2010', 'Michael Jordan', 'Romantinas');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Džiokeriai', '2009', 'Karbauskis', 'Kriminalas');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Devyniai broliai ir jų sesuo', '2005', 'Maldeikiene', 'Pasaka');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Titanicas', '1999', 'Leo', 'Drama');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Konanas', '1999', 'Arnold Shwanzznagger', 'Veiksmo');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Monarchai', '2015', 'Tyus Edney', 'Istorinis');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Meiles Menas', '2011', 'Jackie Chan', 'Romantinis');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Lietuviškos paraštės', '2000', 'Samuel L. Jackson', 'Siaubas');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Gugeliukai', '2015', 'Rocky Balboa', 'Vaikams');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Mazasis Princas', '2007', 'Vladimir Putin', 'Nuotykiu');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('KGB Vaikai', '2016', 'Egidijus Masiulis', 'Veiksmo');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Liutas Karalius', '2011', 'Nes Paksas Geriausias', 'Vaikams');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Skaičiai valdo pasaulį', '2015', 'Donald Trump', 'Siaubo');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Mažasis laiko vagis', '2009', 'Timinskas', 'Nuotykiu');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Lapė ir kaliošai', '2015', 'Sony Weems', 'Nuotykiu');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Ka veiki vaikų darželyje', '2015', 'Lekavicius', 'Vaikams');
INSERT INTO `knygos`.`books` (`title`, `release_date`, `author`, `genre`) VALUES ('Vienas namuose', '1999', 'McCaulkin', 'Nuotykiu');